services:
  backend:
    build:
      context: ../db-project2/src
      dockerfile: Dockerfile
    container_name: editorial-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: editorial-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ../db-project2/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: editorial
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d editorial"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: editorial-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
